name: ci
on: [push,pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into working directory
        uses: actions/checkout@v2
      
      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 8
          java-package: jdk
          architecture: x64
      
      - name: Check Java Version
        run: java -version

      - name: Check Maven Version
        run: mvn -version
      
      - name: Run JUnit Tests
        run: /usr/lib/jvm/java-8-openjdk-amd64/bin/java -ea -Dfile.encoding=ISO-8859-1 -classpath /opt/data/seis635-tp1/SkunkProject/bin:/opt/data/seis635-tp1/SkunkProject/lib/stdlib-package.jar:/snap/eclipse/40/plugins/org.junit.jupiter.api_5.4.0.v20190212-2109.jar:/snap/eclipse/40/plugins/org.junit.jupiter.engine_5.4.0.v20190212-2109.jar:/snap/eclipse/40/plugins/org.junit.jupiter.migrationsupport_5.4.0.v20190212-2109.jar:/snap/eclipse/40/plugins/org.junit.jupiter.params_5.4.0.v20190212-2109.jar:/snap/eclipse/40/plugins/org.junit.platform.commons_1.4.0.v20190212-2109.jar:/snap/eclipse/40/plugins/org.junit.platform.engine_1.4.0.v20190212-2109.jar:/snap/eclipse/40/plugins/org.junit.platform.launcher_1.4.0.v20190212-2109.jar:/snap/eclipse/40/plugins/org.junit.platform.runner_1.4.0.v20190212-2109.jar:/snap/eclipse/40/plugins/org.junit.platform.suite.api_1.4.0.v20190212-2109.jar:/snap/eclipse/40/plugins/org.junit.vintage.engine_5.4.0.v20190212-2109.jar:/snap/eclipse/40/plugins/org.opentest4j_1.1.1.v20190212-2109.jar:/snap/eclipse/40/plugins/org.apiguardian_1.0.0.v20190212-2109.jar:/snap/eclipse/40/plugins/org.junit_4.12.0.v201504281640/junit.jar:/snap/eclipse/40/plugins/org.hamcrest.core_1.3.0.v20180420-1519.jar:/home/vagrant/.eclipse/360744294_linux_gtk_x86_64/configuration/org.eclipse.osgi/218/0/.cp:/home/vagrant/.eclipse/360744294_linux_gtk_x86_64/configuration/org.eclipse.osgi/216/0/.cp org.eclipse.jdt.internal.junit.runner.RemoteTestRunner -version 3 -port 40273 -testLoaderClass org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader -loaderpluginname org.eclipse.jdt.junit5.runtime -packageNameFile /tmp/packageNames1727926611115223060.txt
